name: Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.1' 

    - name: Update
      run: git submodule update --init --recursive
    - name: Build
      run: hugo --minify
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ninoho/ninoho.github.io
        publish_branch: main
        publish_dir: ./public
